### ISSUE TITLE
MatLabのコマンドプロンプトでエラー

### ISSUE THREAD

**Issue by onenechan** [onenechan/research_pinning#1]
Matlabを起動してしばらくすると下記のエラーが出て、極端に動作が遅くなりmatlabが機能しなくなってしまう。
Macの初期化を行なったところしばらく出なくなっていたのだが再発した。

<img width="1178" alt="スクリーンショット 2022-01-23 19 23 25" src="https://user-images.githubusercontent.com/34408519/150674191-6a59dfee-5a49-4d62-841b-0520871d3cb1.png">

ーテキストー
java.lang.reflect.InvocationTargetException
	at sun.lwawt.macosx.LWCToolkit.invokeAndWait(LWCToolkit.java:649)
	at sun.lwawt.macosx.CInputMethod.attributedSubstringFromRange(CInputMethod.java:586)
Caused by: java.lang.IllegalArgumentException: Invalid range
	at com.mathworks.widgets.SyntaxTextPaneBase$InputMethodRequestsHandler.getCommittedText(SyntaxTextPaneBase.java:1980)
	at sun.awt.im.InputMethodContext.getCommittedText(InputMethodContext.java:301)
	at sun.lwawt.macosx.CInputMethod$3.run(CInputMethod.java:598)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by onenechan** [comment]
Javaをインストールしたことが原因のよう。
コードを実行する前に日本語のキーボードにしているとエラーになるらしい......。

https://jp.mathworks.com/matlabcentral/answers/335162-report-a-bug-of-r2017a-on-macbook-pro-2016-java-lang-reflect-invocationtargetexception
